
user  www-data;
worker_processes  2;
daemon off;

error_log  /var/log/nginx/error.log notice;
pid        /run/nginx/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    types {
        font/ttf ttf;
        font/otf otf;
        font/woff woff;
        font/woff2 woff2;
    }

    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp_path;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    gzip  on;
    gzip_disable msie6;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied any;
    gzip_types text/css application/javascript text/xml application/xml font/ttf font/otf font/woff;

    server_tokens off;

    upstream _php {
        server unix:/run/php/php-fpm.sock;
    }

    server {
        listen 80 default_server;
        server_name _;

        root /var/www/public;
        index index.php;

        charset utf-8;

        # Don't add css and js files, see https://livewire.laravel.com/docs/4.x/installation#livewire-javascript-not-loading-404-error
        location ~* \.(png|jpg|jpeg|svg|webp)$ {
            etag on;
            add_header Cache-Control 'private, no-cache';
        }

        location ~* \.(ttf|otf|woff|woff2)$ {
            etag off;
            add_header Cache-Control 'max-age=31536000';
        }

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location = /favicon.ico { access_log off; log_not_found off; }

        error_page 404 /index.php;

        location ~ \.php$ {
            fastcgi_pass _php;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            include fastcgi_params;
        }

        location ~ /\.(?!well-known).* {
            deny all;
        }
    }
}
