
[unix_http_server]
file = /var/run/supervisor/supervisor.sock
chmod = 0700

[supervisord]
logfile = /var/log/supervisor/supervisord.log
pidfile = /var/run/supervisor/supervisord.pid
childlogdir = /var/log/supervisor
user = www-data

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl = unix:///var/run/supervisor/supervisor.sock



[program:nginx]
command = /usr/sbin/nginx
priority = 30
pidfile = /run/nginx/nginx.pid;
user = www-data
autostart = true
autorestart = true


[program:php-fpm]
command = /usr/sbin/php-fpm8.5 -F
priority = 20
pidfile = /run/php/php-fpm.pid
user = www-data
autostart = true
autorestart = true


[program:vulnerar-agent]
process_name=%(program_name)s
command=php /var/www/artisan vulnerar:agent
directory=/var/www
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/vulnerar-agent.log


[program:startup]
command = /usr/bin/bash /var/www/docker/files/startup.sh
priority = 10
user = www-data
autostart = true
autorestart = unexpected
startretries = 3
startsecs = 0
stdout_logfile_maxbytes = 0
stdout_logfile = /dev/stdout
redirect_stderr = true
